lib/storeHall_web/router.ex
defmodule StoreHallWeb.Router do
  use StoreHallWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_secure_browser_headers
    plug StoreHall.Plugs.SetUser
  end

  pipeline :csrf do
    plug :protect_from_forgery
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug StoreHallWeb.Plugs.RequireAuth
  end

  scope "/", StoreHallWeb do
    pipe_through [:browser, :csrf, :auth]

    resources "/users", UserController, only: [:edit, :update, :delete] do
      resources "/items", ItemController, only: [:new, :create, :edit, :update, :delete]
      resources "/mails", MailController, only: [:index, :show, :delete]
      resources "/payments", PaymentController, only: [:index, :delete, :show, :new, :create]

      get "/withdraw", PaymentController, :withdraw

      get "/payment/thanks", PaymentController, :thanks
      get "/payment/cancel", PaymentController, :cancel
    end
  end

  scope "/", StoreHallWeb do
    pipe_through [:browser, :csrf]

    get "/robots.txt", SitemapController, :robots
    get "/sitemap.xml.gz", SitemapController, :sitemap
    get "/accept_cookies", CookieConsentController, :agree
    get "/put_session", SessionController, :put_session

    resources "/", ItemController, only: [:index]

    resources "/users", UserController, only: [:index, :show] do
      resources "/items", ItemController, only: [:show]
    end
  end

  scope "/", StoreHallWeb do
    pipe_through [:browser]

    post "/payment/status", PaymentController, :status
  end

  scope "/about", StoreHallWeb do
    pipe_through [:browser, :csrf]

    get "/", AboutController, :index
    get "/terms", AboutController, :terms
    get "/privacy", AboutController, :privacy
    # get "/cookies", AboutController, :cookies
    # get "/sponsor", AboutController, :sponsor
    get "/howto", AboutController, :howto

    get "/*path", Redirector, to: "/about"
  end

  scope "/auth", StoreHallWeb do
    pipe_through [:browser, :csrf]

    get "/delete", AuthController, :delete
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :new
  end

  scope "/", StoreHallWeb do
    pipe_through [:browser, :csrf]

    get "/*path", Redirector, to: "/"
  end

  # Other scopes may use custom stacks.
  # scope "/api", StoreHallWeb do
  #   pipe_through :api
  # end
end

defmodule StoreHallWeb.Redirector do
  use Phoenix.Controller
  require StoreHallWeb.Gettext

  def init(opts), do: opts

  def call(conn, opts) do
    conn
    |> put_status(:moved_permanently)
    |> put_flash(:error, StoreHallWeb.Gettext.gettext("Page not found"))
    |> redirect(opts)
    |> Plug.Conn.halt()
  end
end

lib/storeHall_web/views/layout_view.ex
defmodule StoreHallWeb.LayoutView do
  use StoreHallWeb, :view
  import StoreHallWeb.PageTitle
  alias StoreHall.Marketing.Mails
  alias StoreHall.Items
  alias StoreHall.Comments
  alias StoreHall.Ratings
  alias StoreHall.Payments
end

lib/storeHall_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= csrf_meta_tag() %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no"/>

    <meta property="og:site_name" content="<%= Application.get_env(:storeHall, :about)[:title] %>">
    <meta name="description" content="<%= page_description(assigns) %>">
    <meta property="og:image" content="<%= page_image(assigns) %>">

    <title><%= page_title_with_suffix(assigns) %></title>

    <link rel="canonical" href="<%= Phoenix.Controller.current_url(@conn, %{}) %>">

    <link rel="icon" type="image/x-icon" href="/favicon.ico">
    <link rel="icon" type="image/x-icon" href="/logo.svg">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>">

  </head>

  <body>
    <header>
      <logo>
        <svg class="svg_icon menu_svg_icon" id="logo_icon">
          <use xlink:href="/images/sprite.svg#si-ant-aliwangwang"></use>
        </svg>

        <%= link to: Routes.item_path(@conn, :index), class: "brand-link" do
          Application.get_env(:storeHall, :about)[:title]
        end %>
      </logo>

      <%= render "header.html", conn: @conn, assigns: assigns %>
    </header>

    <main>
      <p class="flash info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="flash error" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>

    <sidebar>
      <%= render "sidebar.html", conn: @conn %>
    </sidebar>

    <footer>
      <%= render "footer.html", conn: @conn %>
    </footer>

    <%= render "templates.html", conn: @conn %>

    <% logged_user_id = get_logged_user_id(@conn) %>
    <script>window.userToken = "<%= assigns[:user_token] %>";</script>
    <script>window.loggedUserId = "<%= logged_user_id %>";</script>
    <script>window.loggedUserChannel = "<%= StoreHallWeb.UsersChannel.topic_prefix() <> if logged_user_id != nil do "/" <> logged_user_id else "/guest_channel" end %>";</script>

    <script src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>

  </body>
</html>

lib/storeHall_web/templates/layout/footer.html.eex
<%= if @conn.private.plug_session["cuf_info"] != nil do %>
  <div id="footer_info">
	  <%= Gettext.gettext("Marketing participants") %>:
		<%= @conn.private.plug_session["cuf_info"][:user_count] %>
		, <%= Gettext.gettext("Items") %>:
		<%= @conn.private.plug_session["cuf_info"][:item_count] %>
	</div>
<% end %>

<%= if @conn.private.plug_session["cu_settings"]["cookie_consent"] == nil do %>
  <div id="cookie_consent">
  	<div>
      <svg class="svg_icon" id="cookie_consent_icon">
        <use xlink:href="/images/sprite.svg#si-ant-info-circle"></use>
      </svg>
  		<span id="cookie_consent_info">
  			<%= Gettext.gettext("We use cookies.") %>
  		</span>
  	</div>
  	<div id="cookie_consent_agree">
  		<span class="button" cookie_consent="agree" >
  			<%= Gettext.gettext("Agree") %>
  		</span>
			<a href="/about/privacy#cookies" id="cookie_consent_info_link">
				<%= Gettext.gettext("Learn more") %>
			</a>
  	</div>
  </div>
<% end %>

lib/storeHall_web/templates/layout/header.html.eex
<% logged_user_id = get_logged_user_id(@conn) %>

<h1>
  <%= page_title(@assigns) %>
</h1>

<notifications>
  <svg class="svg_icon menu_svg_icon">
    <use xlink:href="/images/sprite.svg#si-awesome-bell"></use>
  </svg>
  <span id="alert_new_notification" class="badge"></span>
  <div class="dropdown wider_container">
    <ul>
      <li>
        <ul id="unread_mails">
        </ul>
      </li>

      <li>
        <div id="new_notifications">
      </li>

      <%= if logged_user_id do %>
        <li>
          <%= link to: Routes.user_mail_path(@conn, :index, logged_user_id) do %>
            <svg class="svg_icon">
              <use xlink:href="/images/sprite.svg#si-awesome-envelope"></use>
            </svg>
            <span class="text"><%= Gettext.gettext("View all Messages") %></span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</notifications>

<%= render "help.html", conn: @conn %>

<avatar>
  <%= if get_logged_user_image(@conn) != nil do %>
    <img src="<%= get_logged_user_image(@conn) %>" alt="<%= logged_user_id %>">
  <% else %>
    <svg class="svg_icon menu_svg_icon">
      <use xlink:href="/images/sprite.svg#si-awesome-user"></use>
    </svg>
  <% end %>
  <div class="dropdown">

    <%= if logged_user_id do %>

      <ul>
        <li>
          <%= link to: Routes.user_payment_path(@conn, :new, logged_user_id), id: "credits_banner" do %>
            <span class="text">
              <span id="balance_credits"><%= Plug.Conn.get_session(@conn, :cu_settings)["credits"] || 0 %><span><%= Gettext.gettext(" credits") %>
            </span>
          <% end %>
        </li>
        <li>
          <%= link to: Routes.user_path(@conn, :show, logged_user_id) <> "#info" do %>
            <svg class="svg_icon">
              <use xlink:href="/images/sprite.svg#si-awesome-user"></use>
            </svg>
            <span class="text"><%= Gettext.gettext("Profile") %></span>
          <% end %>
        </li>

        <li>
          <%= link to: Routes.user_path(@conn, :edit, logged_user_id) <> "#settings" do %>
            <svg class="svg_icon">
              <use xlink:href="/images/sprite.svg#si-awesome-cog"></use>
            </svg>
            <span class="text"><%= Gettext.gettext("Settings") %></span>
          <% end %>
        </li>

      <% if false do %>
        <li>
          <%= link to: Routes.user_mail_path(@conn, :index, logged_user_id) do %>
            <svg class="svg_icon">
              <use xlink:href="/images/sprite.svg#si-awesome-envelope"></use>
            </svg>
            <span class="text"><%= Gettext.gettext("Messages") %></span>
          <% end %>
        </li>
      <% end %>

        <li>
          <%= link to: Routes.item_path(@conn, :index) <> "?filter[merchant]=" <> logged_user_id do %>
            <svg class="svg_icon">
              <use xlink:href="/images/sprite.svg#si-awesome-list-ul"></use>
            </svg>
            <span class="text"><%= Gettext.gettext("My Items") %></span>
          <% end %>
        </li>

        <li>
          <%= link to: Routes.user_item_path(@conn, :new, logged_user_id) do %>
            <svg class="svg_icon">
              <use xlink:href="/images/sprite.svg#si-awesome-plus"></use>
            </svg>
            <span class="text"><%= Gettext.gettext("Add Item") %></span>
          <% end %>
        </li>

        <li>
          <%= link to: Routes.auth_path(@conn, :delete) do %>
            <svg class="svg_icon">
              <use xlink:href="/images/sprite.svg#si-awesome-power-off"></use>
            </svg>
            <span class="text"><%= Gettext.gettext("Sign out") %></span>
          <% end %>
        </li>
      </ul>

    <% else %>

    <div class="login_form_container">
      <form class="login_form" action="<%= Routes.auth_path(@conn, :request, "") %>">

        <button type="submit" class="link-button google_bg" formaction='<%= Routes.auth_path(@conn, :request, "google") %>'>
          <svg class="svg_icon google_bg">
            <use xlink:href="/images/sprite.svg#kysi-awesome-google-title"></use>
          </svg>
          <span class="text"><%= Gettext.gettext("Sign in with Google") %></span>
        </button>
        <button type="submit" class="link-button facebook_bg" formaction='<%= Routes.auth_path(@conn, :request, "facebook") %>'>
          <svg class="svg_icon facebook_bg">
            <use xlink:href="/images/sprite.svg#si-awesome-facebook"></use>
          </svg>
          <span class="text"><%= Gettext.gettext("Sign in with Facebook") %></span>
        </button>

        <div class="checkbox_terms">
          <input id="field_terms" type="checkbox" required name="terms">
          <label for="field_terms">
            <%= Gettext.gettext("I accept the ") %>
            <span class="underline">
              <%= Gettext.gettext("Terms and Conditions") %>
              <%= link to: Routes.about_path(@conn, :terms) do %>
                <svg class="svg_icon info_icon">
                  <use xlink:href="/images/sprite.svg#si-awesome-question-circle"></use>
                </svg>
              <% end %>
            </span>
          </label>
        </div>
        <div class="checkbox_terms">
          <input id="field_privacy" type="checkbox" required name="terms">
          <label for="field_privacy">
            <%= Gettext.gettext("I accept the ") %>
            <span class="underline">
              <%= Gettext.gettext("Privacy policy") %>
              <%= link to: Routes.about_path(@conn, :privacy) do %>
                <svg class="svg_icon info_icon">
                  <use xlink:href="/images/sprite.svg#si-awesome-question-circle"></use>
                </svg>
              <% end %>
            </span>
          </label>
        </div>

        <div class="checkbox_terms">
          <input id="field_marketing" marketing_consent="agree" type="checkbox" name="terms">
          <label for="field_marketing">
            <%= Gettext.gettext("I want to participate in the marketing compains by giving my consent for my information to be used acording to the ") %>
            <span class="underline">
              <%= Gettext.gettext("Privacy policy") %>
              <%= link to: Routes.about_path(@conn, :privacy) do %>
                <svg class="svg_icon info_icon">
                  <use xlink:href="/images/sprite.svg#si-awesome-question-circle"></use>
                </svg>
              <% end %>
            </span>
            <%= Gettext.gettext(" and ") %>
            <span class="underline">
              <%= Gettext.gettext("Terms and Conditions") %>
              <%= link to: Routes.about_path(@conn, :terms) do %>
                <svg class="svg_icon info_icon">
                  <use xlink:href="/images/sprite.svg#si-awesome-question-circle"></use>
                </svg>
              <% end %>
            </span>
          </label>
        </div>
      </form>
    </div>

    <% end %>

  </div>
</avatar>

lib/storeHall_web/templates/layout/help.html.eex
<help>
  <svg class="svg_icon menu_svg_icon">
    <use xlink:href="/images/sprite.svg#si-awesome-question-circle"></use>
  </svg>
  <div class="dropdown">
    <ul>
      <li>
        <%= link to: Routes.about_path(@conn, :index) do %>
          <span class="text"><%= Gettext.gettext("About Us") %></span>
        <% end %>
      </li>

      <li>
        <%= link to: Routes.about_path(@conn, :terms) do %>
          <span class="text"><%= Gettext.gettext("Terms") %></span>
        <% end %>
      </li>

      <li>
        <%= link to: Routes.about_path(@conn, :privacy) do %>
          <span class="text"><%= Gettext.gettext("Privacy") %></span>
        <% end %>
      </li>

      <li>
        <%= link to: Routes.about_path(@conn, :index) <> "#sponsor" do %>
          <span class="text"><%= Gettext.gettext("Sponsor") %></span>
        <% end %>
      </li>

      <li>
        <%= link to: Routes.about_path(@conn, :howto) <> "#post" do %>
          <span class="text"><%= Gettext.gettext("How to") %></span>
        <% end %>
      </li>

    </ul>
  </div>
</help>

lib/storeHall_web/templates/layout/pagination.html.eex
<% page_params = @conn.params
    |> Map.delete("id")
    |> Map.delete("user_id")
    |> Map.delete("page")
    |> Plug.Conn.Query.encode() %>

<% anchor = case @add_params do
  "" -> ""
  a -> "&more_" <> @add_params <> "##{a}"
end %>

<% per_page = case @conn.params["per-page"] do
  nil -> 1
  p -> String.to_integer(p)
end %>

<% current_page = case @conn.params["page"] do
  nil -> 1
  p -> String.to_integer(p)
end %>

<ul class="pagination">

  <%= if length(@model) > per_page do %>
      <li class="page-item">
        <a class="next-page-link page-link" href="?<%= page_params %>&page=<%= current_page+1 %><%= anchor %>" rel="next"><%= Gettext.gettext("show more") %></a>
      </li>
  <% end %>

</ul>

lib/storeHall_web/templates/layout/show_more.html.eex
<% params = @conn.params
    # |> Enum.reject(fn {k, _} -> String.match?(k, ~r/show_\w+_/) end)
    # |> Map.new
    |> Plug.Conn.Query.encode()
    |> case do
        "" -> @add_params
        params -> params <> "&" <> @add_params
      end %>

<span class="load-more-topic" id="<%= @add_params %>">
  <button load-more-topic="filter" params="?<%= params %>" ><%= Gettext.gettext("read more") %></button>
</span>

lib/storeHall_web/templates/layout/sidebar.html.eex
<input type="checkbox" id="sidebar_hider" class="collapsible">
<label for="sidebar_hider">
  <svg class="svg_icon sidebar_svg_icon">
    <use xlink:href="/images/sprite.svg#si-awesome-angle-double-right"></use>
  </svg>
</label>
<div>
  <%= render_existing @conn.private.phoenix_view,
          to_string(@conn.private.phoenix_action) <> "_sidebar.html",
            assigns %>
</div>

lib/storeHall_web/templates/layout/templates.html.eex
<template id='item_template' class='template'>
  <%= render StoreHallWeb.ItemView, "index_item.html", item: Items.item_template(), conn: @conn %>
</template>

<template id='mail_template' class='template'>
  <%= render StoreHallWeb.MailView, "index_mail.html", mail: Mails.mail_template(), conn: @conn %>
</template>

<template id='comment_template' class='template'>
  <%= render StoreHallWeb.CommentView, "show.html", comment: Comments.comment_template(), conn: @conn %>
</template>

<template id='rating_template' class='template'>
  <%= render StoreHallWeb.RatingView, "show.html", rating: Ratings.rating_template(), conn: @conn %>
</template>

<template id='payment_template' class='template'>
  <%= render StoreHallWeb.PaymentView, "index_payment.html", payment: Payments.payment_template(), conn: @conn %>
</template>